### ISSUE TITLE
html sections

### ISSUE THREAD

**Issue by rimmesbe** [zdericnina/prj-rev-bwfs-dasmoto#1]
You are naturally separating your HTML into sections. Use `div` tags to make it official:
<img width="122" alt="screen shot 2017-06-28 at 1 57 34 pm" src="https://user-images.githubusercontent.com/9957628/46773683-903b4c00-cccc-11e8-8fed-2b4418c59fd8.png">

https://github.com/zdericnina/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Crafts/index.html#L11-L14

**Comment by zdericnina** [comment]
Fixed with commit b92d8c16cea79d2e69a1a939af3e0d366364d0c3
