### ISSUE TITLE
img tags

### ISSUE THREAD

**Issue by rimmesbe** [zdericnina/prj-rev-bwfs-dasmoto#2]
Image tags are self-closing tags, so you don't need the `</img>` part. Also, try to use alt attributes to describe your images. It helps for accessibility purposes.

https://github.com/zdericnina/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Crafts/index.html#L12

**Comment by zdericnina** [comment]
Fixed with commit b92d8c16cea79d2e69a1a939af3e0d366364d0c3
