### ISSUE TITLE
don't use inline styling

### ISSUE THREAD

**Issue by rimmesbe** [zdericnina/prj-rev-bwfs-dasmoto#3]
Now that we have CSS in our toolbelt we should keep all styling in the stylesheets. Inline styling is inefficient and very hard to overwrite.

https://github.com/zdericnina/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Crafts/index.html#L14

**Comment by zdericnina** [comment]
fixed with commit c519b77d4bfa8fbd86596cc54ddbcd183408b4bd
