### ISSUE TITLE
setting page fonts

### ISSUE THREAD

**Issue by rimmesbe** [zdericnina/prj-rev-bwfs-dasmoto#4]
Rather than setting the same font-family in each selector, you can set the pages default font in one place:
html { font-family: Helvetica; }
Now all elements will inherit this as their default font.

https://github.com/zdericnina/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Crafts/resources/style.css#L2

**Comment by zdericnina** [comment]
fixed with commit 6359dfa4f3e4bdca25958558de603737e58da263
